"""empty message

Revision ID: 4aedc1b20353
Revises: 6cd9c8ab540a
Create Date: 2022-11-28 22:47:27.179705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aedc1b20353'
down_revision = '6cd9c8ab540a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_info', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['client_info'])
        batch_op.create_unique_constraint(None, ['client_ip'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_info', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
