"""empty message

Revision ID: 6872905cd3e9
Revises: a8d27b2969a4
Create Date: 2022-11-27 22:24:37.926071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6872905cd3e9'
down_revision = 'a8d27b2969a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_isp', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_isp')

    # ### end Alembic commands ###
