"""empty message

Revision ID: 6cd9c8ab540a
Revises: ea3e179f40b2
Create Date: 2022-11-28 22:42:34.927523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cd9c8ab540a'
down_revision = 'ea3e179f40b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_info', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['client_ip'])
        batch_op.create_unique_constraint(None, ['client_info'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_info', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
