"""empty message

Revision ID: b97226422ccc
Revises: e51be049d011
Create Date: 2022-11-28 19:12:48.696037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b97226422ccc'
down_revision = 'e51be049d011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_ip', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('client_info', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_info')
    # ### end Alembic commands ###
